/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleType = IDL.Variant({
  'VIP' : IDL.Null,
  'Ambulance' : IDL.Null,
  'Police' : IDL.Null,
  'FireTruck' : IDL.Null,
  'GeneralVehicle' : IDL.Null,
});
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});
export const VehicleId = IDL.Nat;
export const VehicleStatus = IDL.Variant({
  'dispatched' : IDL.Null,
  'available' : IDL.Null,
  'offline' : IDL.Null,
  'enRoute' : IDL.Null,
});
export const VehiclePublic = IDL.Record({
  'id' : VehicleId,
  'status' : VehicleStatus,
  'vehicleType' : VehicleType,
  'location' : Location,
  'currentIncidentId' : IDL.Opt(IDL.Nat),
});
export const IncidentSeverity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const IncidentId = IDL.Nat;
export const IncidentStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'assigned' : IDL.Null,
  'open' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const IncidentPublic = IDL.Record({
  'id' : IncidentId,
  'status' : IncidentStatus,
  'assignedVehicleIds' : IDL.Vec(IDL.Nat),
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'severity' : IncidentSeverity,
  'location' : Location,
  'incidentType' : IDL.Text,
});
export const AnomalyId = IDL.Nat;
export const AnomalyPublic = IDL.Record({
  'id' : AnomalyId,
  'anomalyType' : IDL.Text,
  'detectedAt' : Timestamp,
  'description' : IDL.Text,
  'severity' : IDL.Text,
  'location' : Location,
});
export const ChatMessageId = IDL.Nat;
export const ChatRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : ChatMessageId,
  'content' : IDL.Text,
  'role' : ChatRole,
  'timestamp' : Timestamp,
});
export const EmergencyStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const EmergencyRequestPublic = IDL.Record({
  'status' : EmergencyStatus,
  'vehicleType' : VehicleType,
  'destination' : IDL.Text,
  'requestId' : IDL.Nat,
  'createdAt' : Timestamp,
  'routePoints' : IDL.Vec(Location),
  'statusText' : IDL.Text,
  'destinationLat' : IDL.Float64,
  'destinationLng' : IDL.Float64,
  'requesterId' : IDL.Principal,
  'vehicleId' : IDL.Text,
});
export const SignalConfigPublic = IDL.Record({
  'redDurationSecs' : IDL.Nat,
  'greenDurationSecs' : IDL.Nat,
  'junctionId' : IDL.Text,
  'yellowDurationSecs' : IDL.Nat,
});
export const SegmentId = IDL.Nat;
export const CongestionLevel = IDL.Variant({
  'heavy' : IDL.Null,
  'free' : IDL.Null,
  'blocked' : IDL.Null,
  'moderate' : IDL.Null,
});
export const TrafficSegmentPublic = IDL.Record({
  'id' : SegmentId,
  'startLat' : IDL.Float64,
  'startLng' : IDL.Float64,
  'vehicleCount' : IDL.Nat,
  'congestionLevel' : CongestionLevel,
  'averageSpeedKmh' : IDL.Float64,
  'endLat' : IDL.Float64,
  'endLng' : IDL.Float64,
});
export const TrafficStats = IDL.Record({
  'openIncidents' : IDL.Nat,
  'totalVehicles' : IDL.Nat,
  'avgCongestion' : IDL.Float64,
  'topAnomalies' : IDL.Vec(IDL.Text),
});
export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'EmergencyResponder' : IDL.Null,
  'TrafficPolice' : IDL.Null,
  'GeneralUser' : IDL.Null,
  'ControlPanelAdmin' : IDL.Null,
});
export const RegistrationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserProfilePublic = IDL.Record({
  'principal' : UserId,
  'role' : UserRole,
  'email' : IDL.Text,
  'registrationStatus' : RegistrationStatus,
});
export const RoutePriority = IDL.Variant({
  'emergency' : IDL.Null,
  'normal' : IDL.Null,
});
export const RouteRequest = IDL.Record({
  'destLat' : IDL.Float64,
  'destLng' : IDL.Float64,
  'priority' : RoutePriority,
  'originLat' : IDL.Float64,
  'originLng' : IDL.Float64,
  'requesterId' : IDL.Principal,
  'vehicleId' : IDL.Nat,
});
export const RouteResult = IDL.Record({
  'estimatedTimeMinutes' : IDL.Float64,
  'segments' : IDL.Vec(Location),
  'congestionWarnings' : IDL.Vec(IDL.Text),
});
export const ChatContext = IDL.Record({
  'totalVehicles' : IDL.Nat,
  'recentAnomalies' : IDL.Vec(IDL.Text),
  'activeIncidentCount' : IDL.Nat,
  'avgCongestion' : IDL.Float64,
  'dashboardRole' : IDL.Text,
});

export const idlService = IDL.Service({
  'addVehicle' : IDL.Func([VehicleType, Location], [VehiclePublic], []),
  'approveEmergencyRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'createIncident' : IDL.Func(
      [Location, IncidentSeverity, IDL.Text],
      [IncidentPublic],
      [],
    ),
  'detectAnomalies' : IDL.Func([], [IDL.Vec(AnomalyPublic)], []),
  'getAnomalies' : IDL.Func([], [IDL.Vec(AnomalyPublic)], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getEmergencyRequests' : IDL.Func(
      [],
      [IDL.Vec(EmergencyRequestPublic)],
      ['query'],
    ),
  'getIncidents' : IDL.Func([], [IDL.Vec(IncidentPublic)], ['query']),
  'getSignalConfigs' : IDL.Func([], [IDL.Vec(SignalConfigPublic)], ['query']),
  'getTrafficSegments' : IDL.Func(
      [],
      [IDL.Vec(TrafficSegmentPublic)],
      ['query'],
    ),
  'getTrafficStats' : IDL.Func([], [TrafficStats], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getVehicles' : IDL.Func([], [IDL.Vec(VehiclePublic)], ['query']),
  'registerUser' : IDL.Func([IDL.Text, UserRole], [UserProfilePublic], []),
  'rejectEmergencyRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'requestRoute' : IDL.Func([RouteRequest], [RouteResult], []),
  'resolveIncident' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'sendChatMessage' : IDL.Func([IDL.Text, ChatContext], [ChatMessage], []),
  'submitEmergencyRequest' : IDL.Func(
      [IDL.Text, VehicleType, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'updateIncident' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IncidentSeverity),
        IDL.Opt(IncidentStatus),
        IDL.Opt(IDL.Vec(IDL.Nat)),
      ],
      [IDL.Bool],
      [],
    ),
  'updateSignalConfig' : IDL.Func([SignalConfigPublic], [IDL.Bool], []),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [IDL.Bool], []),
  'updateVehicleStatus' : IDL.Func(
      [IDL.Nat, VehicleStatus, IDL.Opt(IDL.Nat)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleType = IDL.Variant({
    'VIP' : IDL.Null,
    'Ambulance' : IDL.Null,
    'Police' : IDL.Null,
    'FireTruck' : IDL.Null,
    'GeneralVehicle' : IDL.Null,
  });
  const Location = IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 });
  const VehicleId = IDL.Nat;
  const VehicleStatus = IDL.Variant({
    'dispatched' : IDL.Null,
    'available' : IDL.Null,
    'offline' : IDL.Null,
    'enRoute' : IDL.Null,
  });
  const VehiclePublic = IDL.Record({
    'id' : VehicleId,
    'status' : VehicleStatus,
    'vehicleType' : VehicleType,
    'location' : Location,
    'currentIncidentId' : IDL.Opt(IDL.Nat),
  });
  const IncidentSeverity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const IncidentId = IDL.Nat;
  const IncidentStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'assigned' : IDL.Null,
    'open' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const IncidentPublic = IDL.Record({
    'id' : IncidentId,
    'status' : IncidentStatus,
    'assignedVehicleIds' : IDL.Vec(IDL.Nat),
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'severity' : IncidentSeverity,
    'location' : Location,
    'incidentType' : IDL.Text,
  });
  const AnomalyId = IDL.Nat;
  const AnomalyPublic = IDL.Record({
    'id' : AnomalyId,
    'anomalyType' : IDL.Text,
    'detectedAt' : Timestamp,
    'description' : IDL.Text,
    'severity' : IDL.Text,
    'location' : Location,
  });
  const ChatMessageId = IDL.Nat;
  const ChatRole = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const ChatMessage = IDL.Record({
    'id' : ChatMessageId,
    'content' : IDL.Text,
    'role' : ChatRole,
    'timestamp' : Timestamp,
  });
  const EmergencyStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const EmergencyRequestPublic = IDL.Record({
    'status' : EmergencyStatus,
    'vehicleType' : VehicleType,
    'destination' : IDL.Text,
    'requestId' : IDL.Nat,
    'createdAt' : Timestamp,
    'routePoints' : IDL.Vec(Location),
    'statusText' : IDL.Text,
    'destinationLat' : IDL.Float64,
    'destinationLng' : IDL.Float64,
    'requesterId' : IDL.Principal,
    'vehicleId' : IDL.Text,
  });
  const SignalConfigPublic = IDL.Record({
    'redDurationSecs' : IDL.Nat,
    'greenDurationSecs' : IDL.Nat,
    'junctionId' : IDL.Text,
    'yellowDurationSecs' : IDL.Nat,
  });
  const SegmentId = IDL.Nat;
  const CongestionLevel = IDL.Variant({
    'heavy' : IDL.Null,
    'free' : IDL.Null,
    'blocked' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const TrafficSegmentPublic = IDL.Record({
    'id' : SegmentId,
    'startLat' : IDL.Float64,
    'startLng' : IDL.Float64,
    'vehicleCount' : IDL.Nat,
    'congestionLevel' : CongestionLevel,
    'averageSpeedKmh' : IDL.Float64,
    'endLat' : IDL.Float64,
    'endLng' : IDL.Float64,
  });
  const TrafficStats = IDL.Record({
    'openIncidents' : IDL.Nat,
    'totalVehicles' : IDL.Nat,
    'avgCongestion' : IDL.Float64,
    'topAnomalies' : IDL.Vec(IDL.Text),
  });
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'EmergencyResponder' : IDL.Null,
    'TrafficPolice' : IDL.Null,
    'GeneralUser' : IDL.Null,
    'ControlPanelAdmin' : IDL.Null,
  });
  const RegistrationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserProfilePublic = IDL.Record({
    'principal' : UserId,
    'role' : UserRole,
    'email' : IDL.Text,
    'registrationStatus' : RegistrationStatus,
  });
  const RoutePriority = IDL.Variant({
    'emergency' : IDL.Null,
    'normal' : IDL.Null,
  });
  const RouteRequest = IDL.Record({
    'destLat' : IDL.Float64,
    'destLng' : IDL.Float64,
    'priority' : RoutePriority,
    'originLat' : IDL.Float64,
    'originLng' : IDL.Float64,
    'requesterId' : IDL.Principal,
    'vehicleId' : IDL.Nat,
  });
  const RouteResult = IDL.Record({
    'estimatedTimeMinutes' : IDL.Float64,
    'segments' : IDL.Vec(Location),
    'congestionWarnings' : IDL.Vec(IDL.Text),
  });
  const ChatContext = IDL.Record({
    'totalVehicles' : IDL.Nat,
    'recentAnomalies' : IDL.Vec(IDL.Text),
    'activeIncidentCount' : IDL.Nat,
    'avgCongestion' : IDL.Float64,
    'dashboardRole' : IDL.Text,
  });
  
  return IDL.Service({
    'addVehicle' : IDL.Func([VehicleType, Location], [VehiclePublic], []),
    'approveEmergencyRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'createIncident' : IDL.Func(
        [Location, IncidentSeverity, IDL.Text],
        [IncidentPublic],
        [],
      ),
    'detectAnomalies' : IDL.Func([], [IDL.Vec(AnomalyPublic)], []),
    'getAnomalies' : IDL.Func([], [IDL.Vec(AnomalyPublic)], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getEmergencyRequests' : IDL.Func(
        [],
        [IDL.Vec(EmergencyRequestPublic)],
        ['query'],
      ),
    'getIncidents' : IDL.Func([], [IDL.Vec(IncidentPublic)], ['query']),
    'getSignalConfigs' : IDL.Func([], [IDL.Vec(SignalConfigPublic)], ['query']),
    'getTrafficSegments' : IDL.Func(
        [],
        [IDL.Vec(TrafficSegmentPublic)],
        ['query'],
      ),
    'getTrafficStats' : IDL.Func([], [TrafficStats], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getVehicles' : IDL.Func([], [IDL.Vec(VehiclePublic)], ['query']),
    'registerUser' : IDL.Func([IDL.Text, UserRole], [UserProfilePublic], []),
    'rejectEmergencyRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'requestRoute' : IDL.Func([RouteRequest], [RouteResult], []),
    'resolveIncident' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'sendChatMessage' : IDL.Func([IDL.Text, ChatContext], [ChatMessage], []),
    'submitEmergencyRequest' : IDL.Func(
        [IDL.Text, VehicleType, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'updateIncident' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IncidentSeverity),
          IDL.Opt(IncidentStatus),
          IDL.Opt(IDL.Vec(IDL.Nat)),
        ],
        [IDL.Bool],
        [],
      ),
    'updateSignalConfig' : IDL.Func([SignalConfigPublic], [IDL.Bool], []),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [IDL.Bool], []),
    'updateVehicleStatus' : IDL.Func(
        [IDL.Nat, VehicleStatus, IDL.Opt(IDL.Nat)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };