/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnomalyId = bigint;
export interface AnomalyPublic {
  'id' : AnomalyId,
  'anomalyType' : string,
  'detectedAt' : Timestamp,
  'description' : string,
  'severity' : string,
  'location' : Location,
}
export interface ChatContext {
  'totalVehicles' : bigint,
  'recentAnomalies' : Array<string>,
  'activeIncidentCount' : bigint,
  'avgCongestion' : number,
  'dashboardRole' : string,
}
export interface ChatMessage {
  'id' : ChatMessageId,
  'content' : string,
  'role' : ChatRole,
  'timestamp' : Timestamp,
}
export type ChatMessageId = bigint;
export type ChatRole = { 'user' : null } |
  { 'assistant' : null };
export type CongestionLevel = { 'heavy' : null } |
  { 'free' : null } |
  { 'blocked' : null } |
  { 'moderate' : null };
export interface EmergencyRequestPublic {
  'status' : EmergencyStatus,
  'vehicleType' : VehicleType,
  'destination' : string,
  'requestId' : bigint,
  'createdAt' : Timestamp,
  'routePoints' : Array<Location>,
  'statusText' : string,
  'destinationLat' : number,
  'destinationLng' : number,
  'requesterId' : Principal,
  'vehicleId' : string,
}
export type EmergencyStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type IncidentId = bigint;
export interface IncidentPublic {
  'id' : IncidentId,
  'status' : IncidentStatus,
  'assignedVehicleIds' : Array<bigint>,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'severity' : IncidentSeverity,
  'location' : Location,
  'incidentType' : string,
}
export type IncidentSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type IncidentStatus = { 'resolved' : null } |
  { 'assigned' : null } |
  { 'open' : null };
export interface Location { 'lat' : number, 'lng' : number }
export type RegistrationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type RoutePriority = { 'emergency' : null } |
  { 'normal' : null };
export interface RouteRequest {
  'destLat' : number,
  'destLng' : number,
  'priority' : RoutePriority,
  'originLat' : number,
  'originLng' : number,
  'requesterId' : Principal,
  'vehicleId' : bigint,
}
export interface RouteResult {
  'estimatedTimeMinutes' : number,
  'segments' : Array<Location>,
  'congestionWarnings' : Array<string>,
}
export type SegmentId = bigint;
export interface SignalConfigPublic {
  'redDurationSecs' : bigint,
  'greenDurationSecs' : bigint,
  'junctionId' : string,
  'yellowDurationSecs' : bigint,
}
export type Timestamp = bigint;
export interface TrafficSegmentPublic {
  'id' : SegmentId,
  'startLat' : number,
  'startLng' : number,
  'vehicleCount' : bigint,
  'congestionLevel' : CongestionLevel,
  'averageSpeedKmh' : number,
  'endLat' : number,
  'endLng' : number,
}
export interface TrafficStats {
  'openIncidents' : bigint,
  'totalVehicles' : bigint,
  'avgCongestion' : number,
  'topAnomalies' : Array<string>,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'principal' : UserId,
  'role' : UserRole,
  'email' : string,
  'registrationStatus' : RegistrationStatus,
}
export type UserRole = { 'EmergencyResponder' : null } |
  { 'TrafficPolice' : null } |
  { 'GeneralUser' : null } |
  { 'ControlPanelAdmin' : null };
export type VehicleId = bigint;
export interface VehiclePublic {
  'id' : VehicleId,
  'status' : VehicleStatus,
  'vehicleType' : VehicleType,
  'location' : Location,
  'currentIncidentId' : [] | [bigint],
}
export type VehicleStatus = { 'dispatched' : null } |
  { 'available' : null } |
  { 'offline' : null } |
  { 'enRoute' : null };
export type VehicleType = { 'VIP' : null } |
  { 'Ambulance' : null } |
  { 'Police' : null } |
  { 'FireTruck' : null } |
  { 'GeneralVehicle' : null };
export interface _SERVICE {
  'addVehicle' : ActorMethod<[VehicleType, Location], VehiclePublic>,
  'approveEmergencyRequest' : ActorMethod<[bigint], boolean>,
  'createIncident' : ActorMethod<
    [Location, IncidentSeverity, string],
    IncidentPublic
  >,
  'detectAnomalies' : ActorMethod<[], Array<AnomalyPublic>>,
  'getAnomalies' : ActorMethod<[], Array<AnomalyPublic>>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getEmergencyRequests' : ActorMethod<[], Array<EmergencyRequestPublic>>,
  'getIncidents' : ActorMethod<[], Array<IncidentPublic>>,
  'getSignalConfigs' : ActorMethod<[], Array<SignalConfigPublic>>,
  'getTrafficSegments' : ActorMethod<[], Array<TrafficSegmentPublic>>,
  'getTrafficStats' : ActorMethod<[], TrafficStats>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getVehicles' : ActorMethod<[], Array<VehiclePublic>>,
  'registerUser' : ActorMethod<[string, UserRole], UserProfilePublic>,
  'rejectEmergencyRequest' : ActorMethod<[bigint], boolean>,
  'requestRoute' : ActorMethod<[RouteRequest], RouteResult>,
  'resolveIncident' : ActorMethod<[bigint], boolean>,
  'sendChatMessage' : ActorMethod<[string, ChatContext], ChatMessage>,
  'submitEmergencyRequest' : ActorMethod<
    [string, VehicleType, string, number, number],
    bigint
  >,
  'updateIncident' : ActorMethod<
    [
      bigint,
      [] | [IncidentSeverity],
      [] | [IncidentStatus],
      [] | [Array<bigint>],
    ],
    boolean
  >,
  'updateSignalConfig' : ActorMethod<[SignalConfigPublic], boolean>,
  'updateUserRole' : ActorMethod<[Principal, UserRole], boolean>,
  'updateVehicleStatus' : ActorMethod<
    [bigint, VehicleStatus, [] | [bigint]],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];