/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    lat: number;
    lng: number;
}
export type SegmentId = bigint;
export type Timestamp = bigint;
export interface SignalConfigPublic {
    redDurationSecs: bigint;
    greenDurationSecs: bigint;
    junctionId: string;
    yellowDurationSecs: bigint;
}
export type IncidentId = bigint;
export interface RouteResult {
    estimatedTimeMinutes: number;
    segments: Array<Location>;
    congestionWarnings: Array<string>;
}
export interface RouteRequest {
    destLat: number;
    destLng: number;
    priority: RoutePriority;
    originLat: number;
    originLng: number;
    requesterId: Principal;
    vehicleId: bigint;
}
export interface ChatMessage {
    id: ChatMessageId;
    content: string;
    role: ChatRole;
    timestamp: Timestamp;
}
export interface TrafficStats {
    openIncidents: bigint;
    totalVehicles: bigint;
    avgCongestion: number;
    topAnomalies: Array<string>;
}
export type VehicleId = bigint;
export interface VehiclePublic {
    id: VehicleId;
    status: VehicleStatus;
    vehicleType: VehicleType;
    location: Location;
    currentIncidentId?: bigint;
}
export type ChatMessageId = bigint;
export interface EmergencyRequestPublic {
    status: EmergencyStatus;
    vehicleType: VehicleType;
    destination: string;
    requestId: bigint;
    createdAt: Timestamp;
    routePoints: Array<Location>;
    statusText: string;
    destinationLat: number;
    destinationLng: number;
    requesterId: Principal;
    vehicleId: string;
}
export interface IncidentPublic {
    id: IncidentId;
    status: IncidentStatus;
    assignedVehicleIds: Array<bigint>;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    severity: IncidentSeverity;
    location: Location;
    incidentType: string;
}
export interface AnomalyPublic {
    id: AnomalyId;
    anomalyType: string;
    detectedAt: Timestamp;
    description: string;
    severity: string;
    location: Location;
}
export type AnomalyId = bigint;
export interface UserProfilePublic {
    principal: UserId;
    role: UserRole;
    email: string;
    registrationStatus: RegistrationStatus;
}
export interface TrafficSegmentPublic {
    id: SegmentId;
    startLat: number;
    startLng: number;
    vehicleCount: bigint;
    congestionLevel: CongestionLevel;
    averageSpeedKmh: number;
    endLat: number;
    endLng: number;
}
export type UserId = Principal;
export interface ChatContext {
    totalVehicles: bigint;
    recentAnomalies: Array<string>;
    activeIncidentCount: bigint;
    avgCongestion: number;
    dashboardRole: string;
}
export enum ChatRole {
    user = "user",
    assistant = "assistant"
}
export enum CongestionLevel {
    heavy = "heavy",
    free = "free",
    blocked = "blocked",
    moderate = "moderate"
}
export enum EmergencyStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum IncidentSeverity {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum IncidentStatus {
    resolved = "resolved",
    assigned = "assigned",
    open = "open"
}
export enum RoutePriority {
    emergency = "emergency",
    normal = "normal"
}
export enum UserRole {
    EmergencyResponder = "EmergencyResponder",
    TrafficPolice = "TrafficPolice",
    GeneralUser = "GeneralUser",
    ControlPanelAdmin = "ControlPanelAdmin"
}
export enum VehicleStatus {
    dispatched = "dispatched",
    available = "available",
    offline = "offline",
    enRoute = "enRoute"
}
export enum VehicleType {
    VIP = "VIP",
    Ambulance = "Ambulance",
    Police = "Police",
    FireTruck = "FireTruck",
    GeneralVehicle = "GeneralVehicle"
}
export interface backendInterface {
    addVehicle(vehicleType: VehicleType, location: Location): Promise<VehiclePublic>;
    approveEmergencyRequest(requestId: bigint): Promise<boolean>;
    createIncident(location: Location, severity: IncidentSeverity, incidentType: string): Promise<IncidentPublic>;
    detectAnomalies(): Promise<Array<AnomalyPublic>>;
    getAnomalies(): Promise<Array<AnomalyPublic>>;
    getChatHistory(): Promise<Array<ChatMessage>>;
    getEmergencyRequests(): Promise<Array<EmergencyRequestPublic>>;
    getIncidents(): Promise<Array<IncidentPublic>>;
    getSignalConfigs(): Promise<Array<SignalConfigPublic>>;
    getTrafficSegments(): Promise<Array<TrafficSegmentPublic>>;
    getTrafficStats(): Promise<TrafficStats>;
    getUserProfile(): Promise<UserProfilePublic | null>;
    getVehicles(): Promise<Array<VehiclePublic>>;
    registerUser(email: string, role: UserRole): Promise<UserProfilePublic>;
    rejectEmergencyRequest(requestId: bigint): Promise<boolean>;
    requestRoute(request: RouteRequest): Promise<RouteResult>;
    resolveIncident(id: bigint): Promise<boolean>;
    sendChatMessage(content: string, ctx: ChatContext): Promise<ChatMessage>;
    submitEmergencyRequest(vehicleId: string, vehicleType: VehicleType, destination: string, destinationLat: number, destinationLng: number): Promise<bigint>;
    updateIncident(id: bigint, severity: IncidentSeverity | null, status: IncidentStatus | null, assignedVehicleIds: Array<bigint> | null): Promise<boolean>;
    updateSignalConfig(config: SignalConfigPublic): Promise<boolean>;
    updateUserRole(target: Principal, newRole: UserRole): Promise<boolean>;
    updateVehicleStatus(id: bigint, status: VehicleStatus, incidentId: bigint | null): Promise<boolean>;
}
import type { ChatMessage as _ChatMessage, ChatMessageId as _ChatMessageId, ChatRole as _ChatRole, CongestionLevel as _CongestionLevel, EmergencyRequestPublic as _EmergencyRequestPublic, EmergencyStatus as _EmergencyStatus, IncidentId as _IncidentId, IncidentPublic as _IncidentPublic, IncidentSeverity as _IncidentSeverity, IncidentStatus as _IncidentStatus, Location as _Location, RegistrationStatus as _RegistrationStatus, RoutePriority as _RoutePriority, RouteRequest as _RouteRequest, SegmentId as _SegmentId, Timestamp as _Timestamp, TrafficSegmentPublic as _TrafficSegmentPublic, UserId as _UserId, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole, VehicleId as _VehicleId, VehiclePublic as _VehiclePublic, VehicleStatus as _VehicleStatus, VehicleType as _VehicleType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addVehicle(arg0: VehicleType, arg1: Location): Promise<VehiclePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addVehicle(to_candid_VehicleType_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_VehiclePublic_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVehicle(to_candid_VehicleType_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_VehiclePublic_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveEmergencyRequest(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveEmergencyRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveEmergencyRequest(arg0);
            return result;
        }
    }
    async createIncident(arg0: Location, arg1: IncidentSeverity, arg2: string): Promise<IncidentPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createIncident(arg0, to_candid_IncidentSeverity_n10(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_IncidentPublic_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIncident(arg0, to_candid_IncidentSeverity_n10(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_IncidentPublic_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async detectAnomalies(): Promise<Array<AnomalyPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.detectAnomalies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.detectAnomalies();
            return result;
        }
    }
    async getAnomalies(): Promise<Array<AnomalyPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnomalies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnomalies();
            return result;
        }
    }
    async getChatHistory(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmergencyRequests(): Promise<Array<EmergencyRequestPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyRequests();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyRequests();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncidents(): Promise<Array<IncidentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidents();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidents();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSignalConfigs(): Promise<Array<SignalConfigPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignalConfigs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignalConfigs();
            return result;
        }
    }
    async getTrafficSegments(): Promise<Array<TrafficSegmentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrafficSegments();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrafficSegments();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrafficStats(): Promise<TrafficStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrafficStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrafficStats();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicles(): Promise<Array<VehiclePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicles();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicles();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: UserRole): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, to_candid_UserRole_n41(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UserProfilePublic_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, to_candid_UserRole_n41(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UserProfilePublic_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectEmergencyRequest(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectEmergencyRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectEmergencyRequest(arg0);
            return result;
        }
    }
    async requestRoute(arg0: RouteRequest): Promise<RouteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.requestRoute(to_candid_RouteRequest_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestRoute(to_candid_RouteRequest_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async resolveIncident(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveIncident(arg0);
            return result;
        }
    }
    async sendChatMessage(arg0: string, arg1: ChatContext): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0, arg1);
                return from_candid_ChatMessage_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0, arg1);
            return from_candid_ChatMessage_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitEmergencyRequest(arg0: string, arg1: VehicleType, arg2: string, arg3: number, arg4: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEmergencyRequest(arg0, to_candid_VehicleType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEmergencyRequest(arg0, to_candid_VehicleType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async updateIncident(arg0: bigint, arg1: IncidentSeverity | null, arg2: IncidentStatus | null, arg3: Array<bigint> | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIncident(arg0, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n51(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIncident(arg0, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n51(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateSignalConfig(arg0: SignalConfigPublic): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSignalConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSignalConfig(arg0);
            return result;
        }
    }
    async updateUserRole(arg0: Principal, arg1: UserRole): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n41(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n41(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVehicleStatus(arg0: bigint, arg1: VehicleStatus, arg2: bigint | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVehicleStatus(arg0, to_candid_VehicleStatus_n52(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVehicleStatus(arg0, to_candid_VehicleStatus_n52(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_ChatMessage_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ChatRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatRole): ChatRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_CongestionLevel_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CongestionLevel): CongestionLevel {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_EmergencyRequestPublic_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmergencyRequestPublic): EmergencyRequestPublic {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_EmergencyStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmergencyStatus): EmergencyStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_IncidentPublic_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentPublic): IncidentPublic {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_IncidentSeverity_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentSeverity): IncidentSeverity {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_IncidentStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentStatus): IncidentStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationStatus): RegistrationStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_TrafficSegmentPublic_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrafficSegmentPublic): TrafficSegmentPublic {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_VehiclePublic_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehiclePublic): VehiclePublic {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleStatus): VehicleStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _IncidentId;
    status: _IncidentStatus;
    assignedVehicleIds: Array<bigint>;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    severity: _IncidentSeverity;
    location: _Location;
    incidentType: string;
}): {
    id: IncidentId;
    status: IncidentStatus;
    assignedVehicleIds: Array<bigint>;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    severity: IncidentSeverity;
    location: Location;
    incidentType: string;
} {
    return {
        id: value.id,
        status: from_candid_IncidentStatus_n14(_uploadFile, _downloadFile, value.status),
        assignedVehicleIds: value.assignedVehicleIds,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        severity: from_candid_IncidentSeverity_n16(_uploadFile, _downloadFile, value.severity),
        location: value.location,
        incidentType: value.incidentType
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ChatMessageId;
    content: string;
    role: _ChatRole;
    timestamp: _Timestamp;
}): {
    id: ChatMessageId;
    content: string;
    role: ChatRole;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        content: value.content,
        role: from_candid_ChatRole_n21(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _EmergencyStatus;
    vehicleType: _VehicleType;
    destination: string;
    requestId: bigint;
    createdAt: _Timestamp;
    routePoints: Array<_Location>;
    statusText: string;
    destinationLat: number;
    destinationLng: number;
    requesterId: Principal;
    vehicleId: string;
}): {
    status: EmergencyStatus;
    vehicleType: VehicleType;
    destination: string;
    requestId: bigint;
    createdAt: Timestamp;
    routePoints: Array<Location>;
    statusText: string;
    destinationLat: number;
    destinationLng: number;
    requesterId: Principal;
    vehicleId: string;
} {
    return {
        status: from_candid_EmergencyStatus_n26(_uploadFile, _downloadFile, value.status),
        vehicleType: from_candid_VehicleType_n7(_uploadFile, _downloadFile, value.vehicleType),
        destination: value.destination,
        requestId: value.requestId,
        createdAt: value.createdAt,
        routePoints: value.routePoints,
        statusText: value.statusText,
        destinationLat: value.destinationLat,
        destinationLng: value.destinationLng,
        requesterId: value.requesterId,
        vehicleId: value.vehicleId
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SegmentId;
    startLat: number;
    startLng: number;
    vehicleCount: bigint;
    congestionLevel: _CongestionLevel;
    averageSpeedKmh: number;
    endLat: number;
    endLng: number;
}): {
    id: SegmentId;
    startLat: number;
    startLng: number;
    vehicleCount: bigint;
    congestionLevel: CongestionLevel;
    averageSpeedKmh: number;
    endLat: number;
    endLng: number;
} {
    return {
        id: value.id,
        startLat: value.startLat,
        startLng: value.startLng,
        vehicleCount: value.vehicleCount,
        congestionLevel: from_candid_CongestionLevel_n32(_uploadFile, _downloadFile, value.congestionLevel),
        averageSpeedKmh: value.averageSpeedKmh,
        endLat: value.endLat,
        endLng: value.endLng
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    role: _UserRole;
    email: string;
    registrationStatus: _RegistrationStatus;
}): {
    principal: UserId;
    role: UserRole;
    email: string;
    registrationStatus: RegistrationStatus;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n37(_uploadFile, _downloadFile, value.role),
        email: value.email,
        registrationStatus: from_candid_RegistrationStatus_n39(_uploadFile, _downloadFile, value.registrationStatus)
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VehicleId;
    status: _VehicleStatus;
    vehicleType: _VehicleType;
    location: _Location;
    currentIncidentId: [] | [bigint];
}): {
    id: VehicleId;
    status: VehicleStatus;
    vehicleType: VehicleType;
    location: Location;
    currentIncidentId?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_VehicleStatus_n5(_uploadFile, _downloadFile, value.status),
        vehicleType: from_candid_VehicleType_n7(_uploadFile, _downloadFile, value.vehicleType),
        location: value.location,
        currentIncidentId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.currentIncidentId))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    assigned: null;
} | {
    open: null;
}): IncidentStatus {
    return "resolved" in value ? IncidentStatus.resolved : "assigned" in value ? IncidentStatus.assigned : "open" in value ? IncidentStatus.open : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): IncidentSeverity {
    return "low" in value ? IncidentSeverity.low : "high" in value ? IncidentSeverity.high : "critical" in value ? IncidentSeverity.critical : "medium" in value ? IncidentSeverity.medium : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): ChatRole {
    return "user" in value ? ChatRole.user : "assistant" in value ? ChatRole.assistant : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): EmergencyStatus {
    return "pending" in value ? EmergencyStatus.pending : "approved" in value ? EmergencyStatus.approved : "rejected" in value ? EmergencyStatus.rejected : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heavy: null;
} | {
    free: null;
} | {
    blocked: null;
} | {
    moderate: null;
}): CongestionLevel {
    return "heavy" in value ? CongestionLevel.heavy : "free" in value ? CongestionLevel.free : "blocked" in value ? CongestionLevel.blocked : "moderate" in value ? CongestionLevel.moderate : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    EmergencyResponder: null;
} | {
    TrafficPolice: null;
} | {
    GeneralUser: null;
} | {
    ControlPanelAdmin: null;
}): UserRole {
    return "EmergencyResponder" in value ? UserRole.EmergencyResponder : "TrafficPolice" in value ? UserRole.TrafficPolice : "GeneralUser" in value ? UserRole.GeneralUser : "ControlPanelAdmin" in value ? UserRole.ControlPanelAdmin : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dispatched: null;
} | {
    available: null;
} | {
    offline: null;
} | {
    enRoute: null;
}): VehicleStatus {
    return "dispatched" in value ? VehicleStatus.dispatched : "available" in value ? VehicleStatus.available : "offline" in value ? VehicleStatus.offline : "enRoute" in value ? VehicleStatus.enRoute : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    VIP: null;
} | {
    Ambulance: null;
} | {
    Police: null;
} | {
    FireTruck: null;
} | {
    GeneralVehicle: null;
}): VehicleType {
    return "VIP" in value ? VehicleType.VIP : "Ambulance" in value ? VehicleType.Ambulance : "Police" in value ? VehicleType.Police : "FireTruck" in value ? VehicleType.FireTruck : "GeneralVehicle" in value ? VehicleType.GeneralVehicle : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmergencyRequestPublic>): Array<EmergencyRequestPublic> {
    return value.map((x)=>from_candid_EmergencyRequestPublic_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncidentPublic>): Array<IncidentPublic> {
    return value.map((x)=>from_candid_IncidentPublic_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrafficSegmentPublic>): Array<TrafficSegmentPublic> {
    return value.map((x)=>from_candid_TrafficSegmentPublic_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VehiclePublic>): Array<VehiclePublic> {
    return value.map((x)=>from_candid_VehiclePublic_n3(_uploadFile, _downloadFile, x));
}
function to_candid_IncidentSeverity_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentSeverity): _IncidentSeverity {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_IncidentStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentStatus): _IncidentStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_RoutePriority_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoutePriority): _RoutePriority {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_RouteRequest_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RouteRequest): _RouteRequest {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleStatus): _VehicleStatus {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentSeverity | null): [] | [_IncidentSeverity] {
    return value === null ? candid_none() : candid_some(to_candid_IncidentSeverity_n10(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentStatus | null): [] | [_IncidentStatus] {
    return value === null ? candid_none() : candid_some(to_candid_IncidentStatus_n49(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<bigint> | null): [] | [Array<bigint>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destLat: number;
    destLng: number;
    priority: RoutePriority;
    originLat: number;
    originLng: number;
    requesterId: Principal;
    vehicleId: bigint;
}): {
    destLat: number;
    destLng: number;
    priority: _RoutePriority;
    originLat: number;
    originLng: number;
    requesterId: Principal;
    vehicleId: bigint;
} {
    return {
        destLat: value.destLat,
        destLng: value.destLng,
        priority: to_candid_RoutePriority_n45(_uploadFile, _downloadFile, value.priority),
        originLat: value.originLat,
        originLng: value.originLng,
        requesterId: value.requesterId,
        vehicleId: value.vehicleId
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentSeverity): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == IncidentSeverity.low ? {
        low: null
    } : value == IncidentSeverity.high ? {
        high: null
    } : value == IncidentSeverity.critical ? {
        critical: null
    } : value == IncidentSeverity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    VIP: null;
} | {
    Ambulance: null;
} | {
    Police: null;
} | {
    FireTruck: null;
} | {
    GeneralVehicle: null;
} {
    return value == VehicleType.VIP ? {
        VIP: null
    } : value == VehicleType.Ambulance ? {
        Ambulance: null
    } : value == VehicleType.Police ? {
        Police: null
    } : value == VehicleType.FireTruck ? {
        FireTruck: null
    } : value == VehicleType.GeneralVehicle ? {
        GeneralVehicle: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    EmergencyResponder: null;
} | {
    TrafficPolice: null;
} | {
    GeneralUser: null;
} | {
    ControlPanelAdmin: null;
} {
    return value == UserRole.EmergencyResponder ? {
        EmergencyResponder: null
    } : value == UserRole.TrafficPolice ? {
        TrafficPolice: null
    } : value == UserRole.GeneralUser ? {
        GeneralUser: null
    } : value == UserRole.ControlPanelAdmin ? {
        ControlPanelAdmin: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoutePriority): {
    emergency: null;
} | {
    normal: null;
} {
    return value == RoutePriority.emergency ? {
        emergency: null
    } : value == RoutePriority.normal ? {
        normal: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentStatus): {
    resolved: null;
} | {
    assigned: null;
} | {
    open: null;
} {
    return value == IncidentStatus.resolved ? {
        resolved: null
    } : value == IncidentStatus.assigned ? {
        assigned: null
    } : value == IncidentStatus.open ? {
        open: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleStatus): {
    dispatched: null;
} | {
    available: null;
} | {
    offline: null;
} | {
    enRoute: null;
} {
    return value == VehicleStatus.dispatched ? {
        dispatched: null
    } : value == VehicleStatus.available ? {
        available: null
    } : value == VehicleStatus.offline ? {
        offline: null
    } : value == VehicleStatus.enRoute ? {
        enRoute: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
